# This playbook serves as a quick way to deploy echo-server project to the remote machine.
# It should work with machines that are using Debian-like OS (e.g. Ubuntu).
#
# This is a very simplistic approach where the playbook will install the latest version of Python.
# Then it will create the virtual environment by a given name, to which it then will install
# the `echoserver` library via pip. After that a user of the remote machine should be able
# to start the instance of the **EchoServer** with the following command:
# ```
# /path/to/venv/bin/python3 -m echoserver
# ```
#
# Notice that this playbook requires the privilege escalation, since it ensures the
# latest Python 3 is installed before creating the virtual environment.
#
# So the playbook should be run like this:
# ```sh
# # By default the virtual environment name is "ansible_venv", but you can change that. Keep in mind that this path is relative to the user's home directory.
# ansible-playbook -v --extra-vars="venv_path=your/path/to/venv" -K utils/deploy-server-to-remote-machine.yml
# ```

# Enter the user password when being asked and that's it.
---

- name: deploy-echoserver
  hosts: all

  vars:
    venv_path: ansible_venv

  tasks:

  - name: Install latest version of Python
    become: true
    ansible.builtin.package:
      name: 
      - python3
      - python3-venv
      - python3-pip
      state: latest

  - name: Check installed version of Python
    ansible.builtin.command:
      cmd: python3 --version
    register: python3_version

  - name: Display the version of Python 3
    ansible.builtin.debug:
      msg: "Installed: {{ python3_version.stdout }}"

  - name: Create virtual environment
    ansible.builtin.command:
      cmd: python3 -m venv {{ venv_path }}
      creates: "{{ venv_path }}/bin/activate"

  - name: Install EchoServer library into the specified (venv)
    ansible.builtin.pip:
      name: schizmone-echoserver
      extra_args: "--index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple"
      virtualenv: "/home/{{ ansible_env.USER }}/{{ venv_path }}/"

  - name: Run pip check to validate dependencies
    ansible.builtin.command:
      cmd: "{{ venv_path }}/bin/python3 -m pip check"

  - name: Check that the library was installed
    ansible.builtin.command:
      cmd: "{{ venv_path }}/bin/python3 -m echoserver --help"

  - name: Notify about the successful deploy
    ansible.builtin.debug:
      msg: "echoserver library was successfully deployed to the virtual environment by the path: '{{ venv_path }}'"
